# Q-Learning, tensorflow impl

- Example comes from <http://mnemstudio.org/path-finding-q-learning-tutorial.htm>
- It can be generalized to other problems, but still simple
- 

In [1]:
import tensorflow as tf
import numpy as np
import random

In [8]:
# constants
gamma = tf.constant(0.8, dtype=tf.float32)
action_space_size = 6
state_space_size = 6
terminal_state = 5
training_episode = 20
testing_episode = 5
max_action_count = 20

In [9]:
# var
r = np.array([[-1, -1, -1, -1, 0, -1], [-1, -1, -1, 0, -1, 100], [-1, -1, -1, 0, -1, -1], [-1, 0, 0, -1, 0, -1], [0, -1, -1, 0, -1, 100], [-1, 0, -1, -1, 0, 100]])
r = tf.constant(r, dtype=tf.float32)

q = tf.Variable(np.zeros((6, 6)), dtype=tf.float32)

In [10]:
# ops
def q_update(state, action):
    return q[state, action].assign(tf.add(r[state, action], tf.multiply(gamma, tf.reduce_max(q[action]))))

In [11]:
init = tf.global_variables_initializer()

In [12]:
with tf.Session() as sess:
    sess.run(init)
    
    # train
    print('Training...')
    for i in range(training_episode):
        state = random.randint(0, state_space_size - 1)
        while (state != terminal_state):    
            action = random.randint(0, action_space_size - 1)
            sess.run(q_update(state, action))
            state = action
        
    # verify
    for i in range(testing_episode):
        # one episode
        print("episode: " + str(i + 1))
    
        # random initial state
        state = random.randint(0, action_space_size - 1)
        print("the robot borns in " + str(state) + ".")
        count = 0
        while (state != terminal_state):
            # prevent endless loop
            if count > max_action_count:
                print('fails')
                break
            
            # choose maximal q-value action randomly
            action = tf.argmax(q[state], 0).eval()
        
            print("the robot goes to " + str(action) + '.')
            state = action
            count = count + 1
    
    

Training...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [-1. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0. -1.  0.  0.  0.]
 [-1. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0. -1.  0.  0.  0.]
 [-1. -1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[   0.    0.   -1.    0.    0.    0.]
 [  -1.   -1.    0.    0.    0.    0.]
 [   0.   -1.    0.    0.   -1.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    